### ISSUE TITLE
could rep/req accept multi listeners?

### ISSUE THREAD

**Issue by DyncKevin** [nanomsg/mangos-v1#345]
I am new for mangos, I am using rep/req
I have multi client to request
and I guess the server side should have same amount connections
but after I debug with GoLand, I found there is only one  listener
I check the source code in core.go
the following code:
if pipe, err := l.l.Accept(); err == nil {
			fmt.Println("serve core get new accept from client");
			l.sock.addPipe(pipe, nil, l)
			fmt.Println("serve core get new accept from client, num of listeners:", len(l.sock.listeners));
		} else if err == ErrClosed {
			return
		}

the listener do not add to l.l.listeners.
Am I clear or is my usage right ? thanks very much

**Comment by gdamore** [comment]
Most of the time, you only want one listener.  That listener can create many pipes.  This is just like normal TCP sockets -- you have one listener socket, but it creates new child sockets for each incoming connections.   Mangos uses a similar paradigm.

But you *can* have multiple listeners if you want to listen on different URLs, and those listeners can be associated with the same socket.

**Comment by gdamore** [comment]
This was just a question, so no code changes needed, closing.
